config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/contact'
  get 'static_pages/home'
  get 'relationships/following'
  get 'relationships/follower'

  devise_for :users
  resources :posts
  resources :relationships, only: [:create, :destroy]

   root 'static_pages#home'
   get 'home' => 'static_pages#home'
   

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	

	validates :user_id, presence: true 
	validates :content, presence: true

	mount_uploader :image, ImageUploader
	
	validates :image, :presence => {:message => ', Please Upload 250x250'}

	validate :image_size_validation, :if => "image?"

	def image_size_validation
	    if image.size > 30.kilobytes
	      errors.add(:base, "Image should be 250x250 or less")
	    end
	 end
	
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base

	belongs_to :following_user, class_name: 'User', foreign_key: :follower_id
	belongs_to :followed_user, class_name: 'User', foreign_key: :following_id

	validates :follower_id, presence: true
	validates :following_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :posts

  has_many :relationships, foreign_key: :follower_id
  has_many :users_followed, through: :relationships, source: :followed_user

  has_many :inverse_relationships, foreign_key: :following_id, class_name: 'Relationship'
  has_many :followers, through: :inverse_relationships, source: :following_user 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :first_name, :last_name, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	
	before_filter :authenticate_user! #This will restrict other get in the application by guesting the url.

	def index
		@post = Post.all	
	end

	def new
		@post = Post.new
	end

	def show
		@post = Post.find(params[:id])	
	end

	def edit
		@post = Post.find(params[:id])

		#unless @post.user == current_user (This block is same as the line below)
		#	redirect_to root_path
		#end
		#redirect_to root_path unless current_user == @post.user
		allow_owner
	end

	def create
		@post = current_user.posts.create(post_params)

		if @post.save
			flash[:notice] = "Your post was successfully created" 
			redirect_to posts_path
		else
			render "new"
		end
	end

	def update
		@post = Post.find(params[:id])
		allow_owner
		if @post.update_attributes(post_params)
			flash[:notice] = "Your post was successfully updated"
			redirect_to posts_path
		else
			render "edit"
		end
	end	

	def destroy
		@post = Post.find(params[:id])
		allow_owner
		@post.destroy
		flash[:notice] = "Your post was successfully deleted"
		redirect_to posts_path
	end


	private
		def post_params
			params.require(:post).permit(:content, :image)
			
		end

		def allow_owner
			redirect_to root_path unless current_user == @post.user
		end


end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

	before_filter :authenticate_user!

	def following
		@relationship = current_user.relationships
	end

	def follower
		@relationship = current_user.relationships
	end

	def create
		@relationship = current_user.relationships.create(following_id: params[:relationship][:following_id])
		flash[:notice] = "You have now followed "
		redirect_to posts_path
	end

	def destroy
		@relationship = Relationship.find(params[:id])
		@relationship.destroy
		flash[:notice] = "You have now unfollowed"
		redirect_to posts_path
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_menu.html.erb
	<% if current_user %>
		
		<small> Welcome <%= current_user.first_name %> <%= current_user.last_name %></small>
		<ul class="nav nav-tabs navbar navbar-inverse ">
			<li class="pull-right"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li> 
			<li class="pull-right"><%= link_to "Home", root_path %></li> 
			<li class="pull-right"><%= link_to "Contact", static_pages_contact_path %></li>
			<li class="pull-right"><%= link_to "View Posts", posts_path %></li>
			<a class="brand" href="/home"><img src="/images/brand.png" onmouseover="this.src='/images/brand2.png'" onmouseout="this.src='/images/brand.png'" /></a>
		</ul>
	<% else %>
	<ul class="nav nav-tabs navbar navbar-inverse ">	
		<li class="pull-right"><%= link_to "Sign up", new_user_registration_path %></li> 
		<li class="pull-right"><%= link_to "Sign In", new_user_session_path %></li>
		<li class="pull-right"><%= link_to "Contact", static_pages_contact_path %></li>
		<a class="brand" href="/home"><img src="/images/brand.png" onmouseover="this.src='/images/brand2.png'" onmouseout="this.src='/images/brand.png'" /></a>
	</ul>
	<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Smilingface</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body class="body">
		
		<div class="container wrap" >
			<%= render "layouts/menu" %>

			<div>
				<p class="notice"><%= notice %></p>
				<p class="alert"><%= alert %></p>
			</div>

			<%= yield %>
			
			
			<p class=" copyr">
				<hr style=" height: 6px; border: 0; box-shadow: inset 0 4px 6px -6px rgba(0,0,0,0.3); " >
                &copy; Company 2014 
                <small class="designer"><a href="http://lkabadesign.org" target="_blank"> LKabaDesign</a></small>
            </p>  

		</div>

	</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :multipart => true } do |f| %>
	<% if @post.errors.any? %>
		<div class="alert">
			<h1>Errors:</h1>
				<ul>
					<% @post.errors.full_messages.each do |message| %>
						<li><%= message %></li>
						
					<%end%>
				</ul>
		</div>
	<%end%>

	<p>
		<%= f.label :content, "Content:" %><br/>
		<%= f.text_area :content, rows: 6 %>
	</p>
	<p>
		<%= f.label :image, "Upload Image: " %>
		<%=f.file_field :image %>
	</p>
	<p>
		<%= f.submit "Submit" %>
	</p>
		
<%end%><br/>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render "form" %>

app/views/posts/index.html.erb
<%= link_to "Create New Post", new_post_path, :class => "btn btn-xs btn-black" %><br/><br/>

<% @post.each do |post| %>
	<p>
		<strong>Post:</strong> <%= post.content %><br/>
		<strong>Created at:</strong> <%= post.created_at %><br/>
		<strong>From:</strong> <%= post.user.email %><br/>
	</p>

	<% if current_user == post.user %>


			<%= link_to "show", post_path(post), :class => "btn btn-xs btn-success" %> |
			<%= link_to "edit", edit_post_path(post), :class => "btn btn-xs btn-info" %> |
			<%= link_to "delelte", post, method: :delete, :class => "btn btn-xs btn-danger", :data => { :confirm => "Are you sure?" } %>
			<%= link_to image_tag(post.image_url.to_s, :width => 60, :class => "right", :style => "border-radius: 15px; border: 2px solid red; margin-left: 90%;" ), post_path(post) %>
	<%end%>
	

	<% if current_user && post.user  != current_user %>
		<% @relationship = current_user.relationships.where(following_id: post.user.id).first %>
		

		<% if @relationship.blank? %>
			<%= form_for :relationship, url: relationships_path do |f| %>
				<%= f.hidden_field :following_id, value: post.user.id %>
				<%= f.submit 'follow' %>
				<%= link_to "show", post_path(post), :class => "btn btn-xs btn-success" %>
				<%= link_to image_tag(post.image_url.to_s, :width => 60, :class => "right", :style => "border-radius: 15px; border: 2px solid red; margin-left: 90%;" ), post_path(post) %>
			<%end%>
		<%else%>
			<%= link_to "unfollow", @relationship, :class => "btn btn-xs btn-default", method: :delete %>
			<%= link_to "show", post_path(post), :class => "btn btn-xs btn-success" %>
			<%= link_to image_tag(post.image_url.to_s, :width => 60, :class => "right", :style => "border-radius: 15px; border: 1px solid #097284; margin-left: 90%;" ), post_path(post) %>
		<%end%>
	<%end%>

<hr style="border:1px solid #097284">
<%end%>
<%= link_to "Go back", root_path, :class => "btn btn-xs btn-black" %><br/><br/>


<!--
<% current_user.posts.each do |post| %>
	<p>
		<strong>Post:</strong> <%= post.content %><br/>
		<strong>Created at:</strong> <%= post.created_at %><br/>
		<strong>From:</strong> <%= post.user.email %><br/>
		<%= link_to "edit", edit_post_path(post) %> |
		<%= link_to "show", post_path(post) %> |
		<%= link_to "delelte", post, method: :delete %>
		<hr/>
	</p>

<%end%>
-->

app/views/posts/new.html.erb
<h1>Create New Post</h1>
<%= render "form" %>

app/views/posts/show.html.erb
<h1>Here is your post</h1>

<em>
	<strong>Post:</strong> <%= @post.content %><br/>
	<strong>Create on:</strong> <%= @post.created_at %><br/>
	<strong>Update on:</strong> <%= @post.updated_at %><br/>
	<strong>User number:</strong> <%= @post.user_id %><br/>
	<strong>Post number:</strong> <%= current_user.posts.count %><br/>
</em>

<%= image_tag @post.image_url.to_s, :width => 200, :class => "right", :style => "margin-left: 50%; border-radius: 15px; border: 1px solid #097284; " %>

<hr style="border:1px solid #097284">
<%= link_to "Back", posts_path, :method => :get, :class => "btn btn-xs btn-black" %><br/><br/>

app/views/relationships/follower.html.erb
<% @relationship.each do |relationship| %> 
	<p>
		<%= relationship.follower_id %>
		
	</p>
	<hr/>
<%end%>
<%= link_to "Go back", root_path, :class => "btn btn-xs btn-black" %><br/><br/>

app/views/relationships/following.html.erb
<% @relationship.each do |relationship| %> 
	<p>
		<%= relationship.following_id %>
		
	</p>
	<hr/>
<%end%>
<%= link_to "Go back", root_path, :class => "btn btn-xs btn-black" %><br/><br/>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<% if current_user %>
	<%= link_to "Create New Post", new_post_path, :class => "btn btn-xs btn-black" %><br/><br/>

	<div>
		<p><%= link_to "Followed by", relationships_follower_path %>: <%= current_user.followers.count %></p>
		<p><%= link_to "Following", relationships_following_path %>: <%= current_user.users_followed.count %></p>
	</div><br/>


<%else%>
	<center>
		<h1>Welcome to Smiling Face </h1>
		<h2>The world largest blogger</h2>
		<h3>We have <%= Post.all.count%> posts in our blog</h3>
		
		<%= button_to "Sign up", new_user_registration_path, :method => :get %>
		<em>For an account</em><br/><br/> 
		
		<%= button_to "Sign In", new_user_session_path, :method => :get %>
		<em>If you already have an account</em>
	</center><br/><br/>
<%end%>